#!/usr/bin/env python3

import sys
import configparser

if len(sys.argv) < 2:
	print(f"Usage:\n{sys.argv[0]} projectfile.ioc8 > gpio_config.h")
	sys.exit(0)

ioc8 = configparser.ConfigParser()
ioc8.optionxform = str
ioc8.read_string("[cfg]\n" + open(sys.argv[1], "r").read())

print(f"// This file is automatically generated by {sys.argv[0]} from {sys.argv[1]}\n")
print('#include "stm8s_gpio.h"\n')

for key, value in ioc8["cfg"].items():
	if len(key.split(".")) != 2:
		continue
	section, option = key.split(".")
	if len(section) < 3:
		continue
	if section[0] != "P":
		continue
	if not section[2:].isdigit():
		continue
	port = section[1]
	gpio = int(section[2:])
	signal = ioc8["cfg"].get(f"P{port}{gpio}.Signal", "")
	if option == "GPIO_Label":
		if signal.find("ADC_IN") == 0:
			adc_chan = int(signal[len("ADC_IN"):])
			print(f"#define {value:20s} ADC1_CHANNEL_{adc_chan}")
		else:
			print(f"#define {value:20s} GPIO{port}, (GPIO_Pin_TypeDef)GPIO_PIN_{gpio}")
